version: '3'
services:

  fin-exchange-manage:
    build:
        context: ./
        dockerfile: ./fin-exchange-manage/Dockerfile
    ports: 
      - "9282:5000"
    depends_on:
      - "db"     
  
  db:
    image: postgres
    environment:
       - POSTGRES_USER=${db_username}
       - POSTGRES_PASSWORD=${db_password}
    ports: 
      - "22011:5432"
    
  
        
        
        
        
