version: '3'
services:

  fin-exchange-manage:
    build:
        context: ./
        dockerfile: ./fin-exchange-manage/Dockerfile
    ports: 
      - "9282:5000"
   
  

    
  
        
        
        
        
